DEBUG=False
REDIS_HOST="127.0.0.1"
REDIS_PORT=6378
REDIS_DB=0

GOBELIEVE_URL = "http://api.gobelieve.io"
ANDROID_APP_ID = 18
ANDROID_APP_SECRET = 'lc83RwzODvxaGELdHiOiOmI4vqWC6GkA'

IOS_APP_ID = 19
IOS_APP_SECRET = '5tFTKsZTYTmrZBCW71JZWOczZQBrxRHK'

