DEBUG=False
REDIS_HOST="127.0.0.1"
REDIS_PORT=6378
REDIS_DB=0

GOBELIEVE_URL = "http://api.gobelieve.io"
BAUHINIA_APP_ID = 17
BAUHINIA_APP_KEY = "lc83RwzODvxaGELdHiOiOmI4vqWC6GkA"
BAUHINIA_APP_SECRET = "5tFTKsZTYTmrZBCW71JZWOczZQBrxRHK"


FACE_APP_ID = 1006
FACE_APP_KEY = "JHYHQiYzbmh98045I94lfe6HqcMsRpUx"
FACE_APP_SECRET = "MCCcLzmBYJRvQcwMQzzOM6nvyFYgwxEO"

IMAGE_PATH = "/data/bauhinia"
