DEBUG=True
REDIS_HOST="192.168.33.10"
REDIS_PORT=6379
REDIS_PASSWORD="123456"
REDIS_DB=0


MYSQL_HOST = "192.168.33.10"
MYSQL_PORT = 3306
MYSQL_AUTOCOMMIT = True
MYSQL_CHARSET = 'utf8'
MYSQL_USER = "root"
MYSQL_PASSWD = ""
MYSQL_DATABASE = "bauhinia"
# host,port,user,password,db,auto_commit,charset
MYSQL = (MYSQL_HOST, MYSQL_PORT, MYSQL_USER, MYSQL_PASSWD, MYSQL_DATABASE, MYSQL_AUTOCOMMIT, MYSQL_CHARSET)


GOBELIEVE_URL = "http://dev.api.gobelieve.io"

BAUHINIA_APP_ID = 17
BAUHINIA_APP_KEY = "lc83RwzODvxaGELdHiOiOmI4vqWC6GkA"
BAUHINIA_APP_SECRET = "5tFTKsZTYTmrZBCW71JZWOczZQBrxRHK"


FACE_APP_ID = 1005
FACE_APP_KEY = "peNQB61YcVD0aVu2mJEBR8ccl51sroQF"
FACE_APP_SECRET = "AEDhci9o9RMgCWcLp72G2FxT8GOWHk8N"


IMAGE_PATH = "/tmp/images"
