DEBUG=True
REDIS_HOST="192.168.33.10"
REDIS_PORT=6379
REDIS_DB=0



GOBELIEVE_URL = "http://dev.api.gobelieve.io"
ANDROID_APP_ID = 18
ANDROID_APP_SECRET = 'lc83RwzODvxaGELdHiOiOmI4vqWC6GkA'

IOS_APP_ID = 19
IOS_APP_SECRET = '5tFTKsZTYTmrZBCW71JZWOczZQBrxRHK'

